const BASE_URL = 'http://localhost:5000/api';
const STATIC_URL = 'http://localhost:5000/static';

const PORTAL_CONTAINER_ID = 'portal-root';

const MIN_PRICE = 1000;
const MAX_PRICE = 300000;

const CATALOGUE_PRODUCTS_PER_PAGE = 8;
const ADMIN_PRODUCTS_PER_PAGE = 7;

const ADMIN_ORDERS_PER_PAGE = 3;
const USER_ORDERS_PER_PAGE = 3;

const REVIEWS_PER_PAGE = 3;

const MAX_UPLOADED_IMAGES = 12;
const ALLOWED_MIMETYPES = ['image/jpeg', 'image/png'];
const MAX_FILE_SIZE = 1024 * 1024;

export {
  BASE_URL,
  STATIC_URL,
  PORTAL_CONTAINER_ID,
  MIN_PRICE,
  MAX_PRICE,
  CATALOGUE_PRODUCTS_PER_PAGE,
  ADMIN_PRODUCTS_PER_PAGE,
  ADMIN_ORDERS_PER_PAGE,
  USER_ORDERS_PER_PAGE,
  REVIEWS_PER_PAGE,
  MAX_UPLOADED_IMAGES,
  ALLOWED_MIMETYPES,
  MAX_FILE_SIZE,
};
